---
- name: Roll Out Keycloak Environment
  hosts: keycloak
  gather_facts: false
  become: true

  vars:
    project_path: /opt/keycloak
    ansible_python_interpreter: /usr/bin/python3
    postgres_version: "15-alpine"
    keycloak_version: "23.0.1"
    nginx_version: "latest"
    POSTGRES_PASSWORD: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
    KEYCLOAK_ADMIN_PASSWORD: "{{ lookup('env', 'KEYCLOAK_ADMIN_PASSWORD') }}"
    

  tasks:      
    - name: Start Docker Compose Services 
      raw: |
        export POSTGRES_PASSWORD={{ POSTGRES_PASSWORD }}
        export KEYCLOAK_ADMIN_PASSWORD={{ KEYCLOAK_ADMIN_PASSWORD }}
        export postgres_version={{ postgres_version }}
        export keycloak_version={{ keycloak_version }}
        export nginx_version={{ nginx_version }}
        cd {{ project_path }} && docker-compose up -d
      become: true