name: Rollout Keycloak Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description:  Terraform apply only
        required: true
        default: "all"
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Set Azure Credentials
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV

    - name: Terraform Init
      env:
        TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        cd terraform
        terraform init

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      env:
        TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        cd terraform
        terraform apply -auto-approve

    - name: Set Up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ADMIN_PRIVATE_KEY }}" > ~/.ssh/id_rsa_wsl
        chmod 600 ~/.ssh/id_rsa_wsl

    - name: Prepare Remote Directory and Copy Files
      run: |
        REMOTE_IP={public_ip_address}
        SSH_KEY=~/.ssh/id_rsa_wsl
        REMOTE_USER=adminuser
    

        ssh -o StrictHostKeyChecking=no -i $SSH_KEY $REMOTE_USER@$REMOTE_IP "sudo mkdir -p /opt/keycloak /var/www/html && sudo chown $REMOTE_USER:$REMOTE_USER /opt/keycloak /var/www/html"
    

        scp -o StrictHostKeyChecking=no -i $SSH_KEY \
          ansible/templates/docker-compose.yml \
          ansible/templates/nginx.conf \
          ansible/static/index.html \
          $REMOTE_USER@$REMOTE_IP:/opt/keycloak/
  
        ssh -o StrictHostKeyChecking=no -i $SSH_KEY $REMOTE_USER@$REMOTE_IP "sudo mv /opt/keycloak/index.html /var/www/html/"
      
  ansible:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
     

    - name: Set Up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ADMIN_PRIVATE_KEY }}" > ~/.ssh/id_rsa_wsl
        chmod 600 ~/.ssh/id_rsa_wsl
    - name: Add Host Key
      run: |
        ssh-keyscan -H {public_ip_address} >> ~/.ssh/known_hosts

    - name: Set Azure Credentials
      run: |
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
        echo "KEYCLOAK_ADMIN_PASSWORD=${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}" >> $GITHUB_ENV
    - name: Run Ansible Playbook
      run: |
        cd ansible
        ansible-playbook -i inventory.yml ro-playbook.yml
